name: djin
version: 0.0.2
author: Philipp Walser
description: Inversion of Control-Container for Dart using the Mirrors-API
homepage: https://github.com/Shihayazad/djin
dev_dependencies:
  unittest: any
